import os
import logging
from datetime import datetime
from typing import Dict, Any
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import subprocess

logger = logging.getLogger(__name__)

class DocumentProcessor:
    """Generate DOCX and PDF documents from FRD data"""
    
    def __init__(self, config):
        self.config = config
        os.makedirs(config.GENERATED_FOLDER, exist_ok=True)
    
    def generate_docx(self, requirement: str, frd_sections: Dict[str, str], 
                      user_info: Dict = None) -> str:
        """Generate DOCX document"""
        try:
            doc = Document()
            
            # Add title
            title = doc.add_heading('Functional Requirements Document', 0)
            title.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
            # Add metadata
            self._add_metadata_section(doc, requirement, user_info)
            
            # Add table of contents (placeholder)
            doc.add_page_break()
            doc.add_heading('Table of Contents', 1)
            doc.add_paragraph('1. Project Overview')
            doc.add_paragraph('2. Scope')
            doc.add_paragraph('3. Functional Requirements')
            doc.add_paragraph('4. Non-Functional Requirements')
            doc.add_paragraph('5. User Roles')
            doc.add_paragraph('6. Use Cases')
            doc.add_paragraph('7. Workflow')
            doc.add_paragraph('8. Acceptance Criteria')
            doc.add_paragraph('9. Traceability Matrix')
            
            # Add sections
            doc.add_page_break()
            self._add_sections(doc, frd_sections)
            
            # Save document
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f'FRD_{timestamp}.docx'
            filepath = os.path.join(self.config.GENERATED_FOLDER, filename)
            doc.save(filepath)
            
            logger.info(f"DOCX document generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Failed to generate DOCX: {str(e)}")
            raise
    
    def _add_metadata_section(self, doc, requirement: str, user_info: Dict = None):
        """Add metadata section to document"""
        doc.add_heading('Document Information', 1)
        
        table = doc.add_table(rows=5, cols=2)
        table.style = 'Light Grid Accent 1'
        
        # Fill metadata
        cell_data = [
            ('Document Type', 'Functional Requirements Document'),
            ('Created Date', datetime.now().strftime('%Y-%m-%d %H:%M:%S')),
            ('Status', 'Draft'),
            ('Project Name', user_info.get('project_name', 'N/A') if user_info else 'N/A'),
            ('Author', user_info.get('author', 'Generated by FRD System') if user_info else 'Generated by FRD System'),
        ]
        
        for i, (key, value) in enumerate(cell_data):
            table.rows[i].cells[0].text = key
            table.rows[i].cells[1].text = value
        
        # Add requirement summary
        doc.add_heading('Requirement Summary', 1)
        doc.add_paragraph(requirement)
    
    def _add_sections(self, doc, frd_sections: Dict[str, str]):
        """Add FRD sections to document"""
        section_order = [
            'Project Overview',
            'Scope',
            'Functional Requirements',
            'Non-Functional Requirements',
            'User Roles',
            'Use Cases',
            'Workflow',
            'Acceptance Criteria',
            'Traceability Matrix'
        ]
        
        for section_name in section_order:
            # Find matching section (case-insensitive)
            content = None
            for key in frd_sections.keys():
                if key.lower() == section_name.lower() or section_name.lower() in key.lower():
                    content = frd_sections[key]
                    break
            
            if content:
                doc.add_page_break()
                doc.add_heading(section_name, 1)
                
                # Handle different content types
                if isinstance(content, list):
                    for item in content:
                        doc.add_paragraph(item, style='List Bullet')
                elif isinstance(content, dict):
                    for key, value in content.items():
                        doc.add_heading(key, 2)
                        doc.add_paragraph(str(value))
                else:
                    # Split by newlines and add as paragraphs
                    for paragraph_text in str(content).split('\n'):
                        if paragraph_text.strip():
                            doc.add_paragraph(paragraph_text)
    
    def generate_pdf(self, docx_filepath: str) -> str:
        """Convert DOCX to PDF using LibreOffice"""
        try:
            # Check if LibreOffice is available
            output_dir = self.config.GENERATED_FOLDER
            filename = os.path.basename(docx_filepath).replace('.docx', '.pdf')
            pdf_filepath = os.path.join(output_dir, filename)
            
            # Try using LibreOffice
            try:
                subprocess.run([
                    'libreoffice',
                    '--headless',
                    '--convert-to', 'pdf',
                    '--outdir', output_dir,
                    docx_filepath
                ], check=True, capture_output=True, timeout=30)
                
                logger.info(f"PDF generated: {pdf_filepath}")
                return pdf_filepath
            except (subprocess.CalledProcessError, FileNotFoundError):
                # Fallback: use python-docx with reportlab
                logger.warning("LibreOffice not available, using reportlab fallback")
                return self._generate_pdf_reportlab(docx_filepath)
            
        except Exception as e:
            logger.error(f"Failed to generate PDF: {str(e)}")
            raise
    
    def _generate_pdf_reportlab(self, docx_filepath: str) -> str:
        """Fallback PDF generation using reportlab"""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.units import inch
            
            # Read DOCX
            doc_obj = Document(docx_filepath)
            
            # Create PDF
            pdf_filepath = docx_filepath.replace('.docx', '.pdf')
            pdf_doc = SimpleDocTemplate(pdf_filepath, pagesize=letter)
            
            elements = []
            styles = getSampleStyleSheet()
            
            # Add content
            for paragraph in doc_obj.paragraphs:
                if paragraph.text:
                    style = styles['Normal']
                    if paragraph.style.name.startswith('Heading'):
                        level = int(paragraph.style.name[-1])
                        style = styles[f'Heading{level}']
                    
                    elements.append(Paragraph(paragraph.text, style))
                    elements.append(Spacer(1, 0.2 * inch))
            
            pdf_doc.build(elements)
            logger.info(f"PDF generated (reportlab): {pdf_filepath}")
            return pdf_filepath
            
        except Exception as e:
            logger.error(f"PDF generation failed: {str(e)}")
            raise
    
    def create_template(self, template_name: str, sections: Dict[str, str]) -> str:
        """Create a reusable template"""
        try:
            template_path = os.path.join(
                self.config.GENERATED_FOLDER,
                f'template_{template_name}.docx'
            )
            
            doc = Document()
            doc.add_heading(f'FRD Template: {template_name}', 0)
            
            for section_name, section_content in sections.items():
                doc.add_heading(section_name, 1)
                doc.add_paragraph(f"[Template: {section_content}]")
            
            doc.save(template_path)
            logger.info(f"Template created: {template_path}")
            return template_path
            
        except Exception as e:
            logger.error(f"Failed to create template: {str(e)}")
            raise
    
    def format_content(self, content: str, format_type: str = 'paragraph') -> str:
        """Format content for better readability"""
        if format_type == 'bullet':
            return '\n'.join(f"• {line.strip()}" for line in content.split('\n') if line.strip())
        elif format_type == 'numbered':
            return '\n'.join(f"{i+1}. {line.strip()}" for i, line in enumerate(content.split('\n')) if line.strip())
        else:
            return content
